os:
  - ubuntu-24.04
  - ubuntu-22.04
  - macos-26-intel
  - macos-26
  - windows-2025
  - windows-2022
toolchain:
  - {compiler: gcc, version: 15}
  - {compiler: gcc, version: 14}
  - {compiler: gcc, version: 13}
  - {compiler: intel, version: '2025.2'}
  - {compiler: intel, version: '2025.0'}
  - {compiler: intel, version: '2024.1'}
  - {compiler: intel, version: '2024.0'}
  - {compiler: intel, version: '2023.2'}
  - {compiler: intel, version: '2023.1'}
  - {compiler: intel, version: '2023.0'}
  - {compiler: intel, version: '2022.2.1'}
  - {compiler: intel, version: '2022.2'}
  - {compiler: intel, version: '2022.1'}
  - {compiler: intel, version: '2022.0'}
  - {compiler: intel, version: '2021.4'}
  - {compiler: intel, version: '2021.2'}
  - {compiler: intel, version: '2021.1.2'}
  - {compiler: intel, version: '2021.1'}
  - {compiler: intel-classic, version: '2021.12'}
  - {compiler: intel-classic, version: '2021.11'}
  - {compiler: intel-classic, version: '2021.10'}
  - {compiler: intel-classic, version: '2021.9'}
  - {compiler: intel-classic, version: '2021.8'}
  - {compiler: intel-classic, version: '2021.7.1'}
  - {compiler: intel-classic, version: '2021.6'}
  - {compiler: intel-classic, version: '2021.5'}
  - {compiler: intel-classic, version: '2021.4'}
  - {compiler: intel-classic, version: '2021.3'}
  - {compiler: intel-classic, version: '2021.2'}
  - {compiler: intel-classic, version: '2021.1.2'}
  - {compiler: intel-classic, version: '2021.1'}
  - {compiler: lfortran, version: '0.58.0'}
  - {compiler: lfortran, version: '0.57.0'}
  - {compiler: nvidia-hpc, version: '26.1'}
  - {compiler: nvidia-hpc, version: '25.9'}
  - {compiler: nvidia-hpc, version: '25.7'}
  - {compiler: nvidia-hpc, version: '25.5'}
  - {compiler: nvidia-hpc, version: '25.3'}
  - {compiler: nvidia-hpc, version: '25.1'}
  - {compiler: nvidia-hpc, version: '24.5'}
  - {compiler: nvidia-hpc, version: '24.3'}
  - {compiler: nvidia-hpc, version: '24.1'}
  - {compiler: nvidia-hpc, version: '23.11'}
  - {compiler: nvidia-hpc, version: '23.9'}
  - {compiler: nvidia-hpc, version: '23.7'}
  - {compiler: nvidia-hpc, version: '23.5'}
  - {compiler: nvidia-hpc, version: '23.3'}
  - {compiler: nvidia-hpc, version: '23.1'}
  - {compiler: aocc, version: '5.1.0'}
exclude:
  # ifx not available on ARM macs
  - os: macos-26
    toolchain: {compiler: intel}
  # nvidia-hpc not available on mac
  - os: macos-26-intel
    toolchain: {compiler: nvidia-hpc}
  - os: macos-26
    toolchain: {compiler: nvidia-hpc}
  # nvidia-hpc not available on windows
  - os: windows-2025
    toolchain: {compiler: nvidia-hpc}
  - os: windows-2022
    toolchain: {compiler: nvidia-hpc}
  # aocc supported only on Ubuntu 24.04
  - os: ubuntu-22.04
    toolchain: {compiler: aocc}
  - os: macos-26-intel
    toolchain: {compiler: aocc}
  - os: macos-26
    toolchain: {compiler: aocc}
  - os: windows-2025
    toolchain: {compiler: aocc}
  - os: windows-2022
    toolchain: {compiler: aocc}
include:
  # macos-14 (ARM): gcc, intel-classic full range, lfortran
  - {os: macos-14, toolchain: {compiler: gcc, version: 15}}
  - {os: macos-14, toolchain: {compiler: gcc, version: 14}}
  - {os: macos-14, toolchain: {compiler: gcc, version: 13}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.12'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.11'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.10'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.9'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.8'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.7.1'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.6'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.5'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.4'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.3'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.2'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.1.2'}}
  - {os: macos-14, toolchain: {compiler: intel-classic, version: '2021.1'}}
  - {os: macos-14, toolchain: {compiler: lfortran, version: '0.58.0'}}
  - {os: macos-14, toolchain: {compiler: lfortran, version: '0.57.0'}}
  # macos-15 (ARM): gcc, intel-classic full range, lfortran
  - {os: macos-15, toolchain: {compiler: gcc, version: 15}}
  - {os: macos-15, toolchain: {compiler: gcc, version: 14}}
  - {os: macos-15, toolchain: {compiler: gcc, version: 13}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.12'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.11'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.10'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.9'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.8'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.7.1'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.6'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.5'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.4'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.3'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.2'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.1.2'}}
  - {os: macos-15, toolchain: {compiler: intel-classic, version: '2021.1'}}
  - {os: macos-15, toolchain: {compiler: lfortran, version: '0.58.0'}}
  - {os: macos-15, toolchain: {compiler: lfortran, version: '0.57.0'}}
  # macos-15-intel: gcc, intel-classic full range, intel full range, lfortran
  - {os: macos-15-intel, toolchain: {compiler: gcc, version: 15}}
  - {os: macos-15-intel, toolchain: {compiler: gcc, version: 14}}
  - {os: macos-15-intel, toolchain: {compiler: gcc, version: 13}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.12'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.11'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.10'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.9'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.8'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.7.1'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.6'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.5'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.4'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.3'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.2'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.1.2'}}
  - {os: macos-15-intel, toolchain: {compiler: intel-classic, version: '2021.1'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2025.2'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2025.0'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2024.1'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2024.0'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2023.2'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2023.1'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2023.0'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2022.2.1'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2022.2'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2022.1'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2022.0'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2021.4'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2021.2'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2021.1.2'}}
  - {os: macos-15-intel, toolchain: {compiler: intel, version: '2021.1'}}
  - {os: macos-15-intel, toolchain: {compiler: lfortran, version: '0.58.0'}}
  - {os: macos-15-intel, toolchain: {compiler: lfortran, version: '0.57.0'}}
