name: Test FC
description: Test Fortran compiler compatibility
inputs:
  compiler:
    description: "Toolchain or compiler to install"
    required: true
  version:
    description: "Version of toolchain or compiler"
    required: true
runs:
  using: "composite"
  steps:

    - name: Check compiler version
      shell: bash
      run: |
        # check $FC == $FPM_FC
        [[ "${{ env.FC }}" == "${{ env.FPM_FC }}" ]] && (echo "FC and FPM_FC match") || (echo "FC and FPM_FC don't match: ${{ env.FC }} != ${{ env.FPM_FC}}"; exit 1)

        # check compiler version
        if ([ "$RUNNER_OS" == "Windows" ] && [[ "${{ inputs.compiler }}" =~ "intel" ]]); then
          # only last line of output captured by command substitution, write to temp file instead
          ${{ env.FC }} //QV > "$RUNNER_TEMP/${{ env.FC }}.ver" 2>&1
          fcv=$(cat "$RUNNER_TEMP/${{ env.FC }}.ver" | head -n 1)
          fcv=${fcv#*Version }
          fcv=${fcv%% Build*}
        elif ([ "$RUNNER_OS" == "Linux" ] && [[ "${{ inputs.compiler }}" == "nvidia-hpc" ]]); then
          # Get the compiler version and extract the version number
          fcv=$(${{ env.FC }} --version 2>&1 | awk '/nvfortran/ {print $2}' | cut -d'-' -f1)
        elif ([[ "${{ inputs.compiler }}" == "lfortran" ]]); then
          fcv=$(${{ env.FC }} --version | head -n 1 | grep -woE '[0123456789.]+')
        elif ([[ "${{ inputs.compiler }}" == "aocc" ]]); then
          # AOCC flang reports LLVM/clang version first; extract AOCC version (e.g. AOCC_4.0.0 or AOCC 5.1.0)
          fcv=$(${{ env.FC }} --version 2>&1 | grep -oE 'AOCC[_ ][0-9]+\.[0-9]+\.[0-9]+' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
        elif ([[ "${{ inputs.compiler }}" != "nvidia-hpc" ]]); then
          fcv=$(${{ env.FC }} --version | head -n 1)
          fcv=$(echo "$fcv" | grep -woE '[0123456789.]+' | head -n 1)
        fi
        [[ "$fcv" == ${{ inputs.version }}* ]] && (echo "found ${{ env.FC }} version: $fcv") || (echo "unexpected ${{ env.FC }} version: $fcv"; exit 1)

    - name: Test compile (bash)
      working-directory: test
      shell: bash
      run: |
        # hello world program
        ${{ env.FC }} -o hw hw.f90
        output=$(./hw '2>&1')
        [[ "$output" == *"hello world"* ]] && echo "$output" || (echo "Unexpected Fortran program 'hw' output: $output"; exit 1)
        rm hw

    - name: Test compile with debug flags (bash)
      working-directory: test
      shell: bash
      run: |
        # Compile with flags that trigger advanced assembler features
        # These flags would have caught the gcc-15 assembler issue (issue #197)
        ${{ env.FC }} -g -fcheck=all -finit-real=snan -ffpe-trap=invalid,zero,overflow -o hw_debug hw.f90
        output=$(./hw_debug 2>&1)
        [[ "$output" == *"hello world"* ]] && echo "$output" || (echo "Unexpected Fortran program 'hw_debug' output: $output"; exit 1)
        rm hw_debug

    - name: Test compile Fortran (pwsh)
      working-directory: test
      # todo: debug lfortran discovery issues (same for powershell and cmd below)
      if: ${{ (success() || failure()) && runner.os == 'Windows' && inputs.compiler != 'lfortran' }}
      shell: pwsh
      run: |
        ${{ env.FC }} -o hw.exe hw.f90 
        $output=$(& ".\hw.exe")
        if ($output -match "hello world") {
            write-output $output
        } else {
            write-output "unexpected output: $output"
            exit 1
        }
        rm hw.exe

    - name: Test compile Fortran (powershell)
      working-directory: test
      if: ${{ (success() || failure()) && runner.os == 'Windows' && inputs.compiler != 'lfortran' }}
      shell: powershell
      run: |
        ${{ env.FC }} -o hw.exe hw.f90 
        $output=$(& ".\hw.exe")
        if ($output -match "hello world") {
            write-output $output
        } else {
            write-output "unexpected output: $output"
            exit 1
        }
        rm hw.exe

    - name: Test compile Fortran (cmd)
      working-directory: test
      if: ${{ (success() || failure()) && runner.os == 'Windows' && inputs.compiler != 'lfortran' }}
      shell: cmd
      run: |
        ${{ env.FC }} -o hw.exe hw.f90 
        for /f "tokens=* usebackq" %%f in (`.\hw.exe`) do @set "OUTPUT=%%f"
        if "%OUTPUT%"=="hello world" (
          echo %OUTPUT%
        ) else (
          echo unexpected output: %OUTPUT%
          exit 1
        )
        del hw.exe
    